name: release
inputs:
  token:
    description: GitHub token
    required: true
runs:
  using: composite
  steps:
  - uses: actions/setup-go@v5
    with:
      go-version: stable
  - run: make release
    shell: bash
    env:
      GITHUB_TOKEN: ${{ inputs.token }}
